{ paletteSet, lib, ... }:
let
  p = paletteSet.palette;
  hex = str: lib.removePrefix "#" str;

  mkFace =
    {
      f ? "default",
      b ? "default",
      a ? "",
    }:
    let
      fStr = if f == "default" then "default" else "rgb:${hex f}";
      bStr = if b == "default" then "default" else "rgb:${hex b}";
      aStr = if a == "" then "" else "+${a}";
    in
    "${fStr},${bStr}${aStr}";

in
{
  "kak/colors/current.kak" =
    # kak
    ''
      # Generated by Nix — do not edit manually.
      # Palette: ${paletteSet.name}
      # Kakoune face reference:
      #    face global <Name> fg,bg+attributes
      #    attributes: b=bold  i=italic  u=underline  c=curly-underline
      #                s=strikethrough  r=reverse  B=blink  d=dim  f=final

      # Core UI
      face global Default            ${
        mkFace {
          f = p.on_background;
          b = p.background;
        }
      }
      face global BufferPadding      ${
        mkFace {
          f = p.outline_variant;
          b = p.background;
        }
      }
      face global NonText            ${mkFace { f = p.outline_variant; }}
      face global Whitespace         ${mkFace { f = p.surface_container_high; }}

      # Line numbers
      face global LineNumbers        ${
        mkFace {
          f = p.gray;
          b = p.surface;
        }
      }
      face global LineNumberCursor   ${
        mkFace {
          f = p.on_primary_container;
          b = p.secondary_container;
          a = "b";
        }
      }

      # Cursors
      face global PrimaryCursor      ${
        mkFace {
          f = p.cursor_fg;
          b = p.cursor_bg;
          a = "b";
        }
      }
      face global SecondaryCursor    ${
        mkFace {
          f = p.cursor_fg;
          b = p.blue;
        }
      }
      face global PrimaryCursorEol   ${
        mkFace {
          f = p.cursor_fg;
          b = p.cursor_bg;
        }
      }
      face global SecondaryCursorEol ${
        mkFace {
          f = p.cursor_fg;
          b = p.blue;
        }
      }

      # Selections
      face global PrimarySelection   ${
        mkFace {
          f = p.selection_fg;
          b = p.selection_bg;
        }
      }
      face global SecondarySelection ${
        mkFace {
          f = p.on_background;
          b = p.surface_container;
        }
      }

      # Matching parens / search
      face global MatchingChar       ${
        mkFace {
          f = p.cursor_fg;
          b = p.blue;
          a = "u";
        }
      }
      face global Search             ${
        mkFace {
          f = p.on_secondary;
          b = p.secondary;
        }
      }
      face global CurrentSearch      ${
        mkFace {
          f = p.on_primary;
          b = p.primary;
          a = "b";
        }
      }

      # Statusline
      face global StatusLine         ${
        mkFace {
          f = p.on_surface;
          b = p.surface_container_low;
        }
      }
      face global StatusLineMode     ${
        mkFace {
          f = p.on_primary;
          b = p.primary;
          a = "b";
        }
      }
      face global StatusLineInfo     ${
        mkFace {
          f = p.outline_variant;
          b = p.surface_container_lowest;
        }
      }
      face global StatusLineValue    ${
        mkFace {
          f = p.builtins;
          b = p.surface_container_low;
        }
      }
      face global StatusCursor       ${
        mkFace {
          f = p.cursor_fg;
          b = p.cursor_bg;
        }
      }

      # Prompt
      face global Prompt             ${
        mkFace {
          f = p.primary;
          a = "b";
        }
      }

      # Menu / completion popup
      face global MenuForeground     ${
        mkFace {
          f = p.on_primary_container;
          b = p.primary_container;
          a = "b";
        }
      }
      face global MenuBackground     ${
        mkFace {
          f = p.on_surface;
          b = p.surface_container;
        }
      }
      face global MenuInfo           ${
        mkFace {
          f = p.inlay;
          b = p.surface_container;
          a = "i";
        }
      }

      # Info box (hover, signature help)
      face global Information        ${
        mkFace {
          f = p.on_surface;
          b = p.surface_container;
        }
      }
      face global InlayHint          ${
        mkFace {
          f = p.inlay;
          a = "i";
        }
      }

      # Diagnostics
      face global DiagnosticError    ${
        mkFace {
          f = p.red;
          a = "c";
        }
      }
      face global DiagnosticWarning  ${
        mkFace {
          f = p.orange;
          a = "c";
        }
      }
      face global DiagnosticInfo     ${
        mkFace {
          f = p.blue;
          a = "c";
        }
      }
      face global DiagnosticHint     ${
        mkFace {
          f = p.cyan;
          a = "c";
        }
      }

      face global Error              ${
        mkFace {
          f = p.on_background;
          b = p.red;
          a = "b";
        }
      }

      # Diff
      face global DiffAdd            ${
        mkFace {
          f = p.green;
          b = p.surface_container_low;
        }
      }
      face global DiffChange         ${
        mkFace {
          f = p.orange;
          b = p.surface_container_low;
        }
      }
      face global DiffDelete         ${
        mkFace {
          f = p.red;
          b = p.surface_container_low;
        }
      }

      # kak-lsp specific
      face global Reference          default,default+u
      face global ReferenceBind      ${
        mkFace {
          f = p.modules;
          a = "u";
        }
      }
      face global CodeLens           ${
        mkFace {
          f = p.inlay;
          a = "i";
        }
      }
      face global CodeLensLink       ${
        mkFace {
          f = p.labels;
          a = "iu";
        }
      }

      # Syntax: comments
      face global comment            ${
        mkFace {
          f = p.comments;
          a = "i";
        }
      }
      face global documentation      ${
        mkFace {
          f = p.inlay;
          a = "i";
        }
      }

      # Syntax: keywords
      face global keyword            ${
        mkFace {
          f = p.keywords;
          a = "b";
        }
      }
      face global operator           ${mkFace { f = p.punctuation; }}
      face global attribute          ${mkFace { f = p.attribute or p.modules; }}
      face global meta               ${mkFace { f = p.macros; }}
      face global module             ${mkFace { f = p.modules; }}

      # Syntax: functions
      face global function           ${mkFace { f = p.functions; }}
      face global builtin            ${
        mkFace {
          f = p.builtins;
          a = "i";
        }
      }

      # Syntax: types
      face global type               ${mkFace { f = p.types; }}

      # Syntax: values / strings
      face global value              ${mkFace { f = p.numeric; }}
      face global string             ${mkFace { f = p.strings; }}

      # Syntax: identifiers / variables
      face global variable           ${mkFace { f = p.on_background; }}
      face global identifier         ${mkFace { f = p.on_background; }}

      # Syntax: markup (markdown, asciidoc, etc.)
      face global header             ${
        mkFace {
          f = p.keywords;
          a = "b";
        }
      }
      face global bold               ${
        mkFace {
          f = p.builtins;
          a = "b";
        }
      }
      face global italic             ${
        mkFace {
          f = p.specials;
          a = "i";
        }
      }
      face global mono               ${mkFace { f = p.strings; }}
      face global block              ${
        mkFace {
          f = p.strings;
          b = p.surface_container_low;
        }
      }
      face global link               ${
        mkFace {
          f = p.labels;
          a = "u";
        }
      }
      face global bullet             ${mkFace { f = p.labels; }}
      face global list               ${mkFace { f = p.on_background; }}

      # Git (gutter markers)
      face global GitGutterAdd       ${
        mkFace {
          f = p.green;
          b = p.background;
        }
      }
      face global GitGutterChange    ${
        mkFace {
          f = p.orange;
          b = p.background;
        }
      }
      face global GitGutterDelete    ${
        mkFace {
          f = p.red;
          b = p.background;
        }
      }
    '';
}
